apiVersion: v1
kind: Secret
metadata:
  name: my-private-ssh-repo1
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: my-repo-creds1
  url: git@github.com:vinaypalvirk51/Caledon.git
  type: git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ74KXxU/Y+pkF+bngE/4UwHaeFY+aLytpgd5q9RSBbq vinaypalvirk51@gmail.com

    -----END OPENSSH PRIVATE KEY-----
