apiVersion: v1
kind: Secret
metadata:
  name: my-private-ssh-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: my-repo-creds
  url: git@github.com:vinaypalvirk51/Caledon.git
  type: git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    SHA256:UJS1TxCZOW9I/w16CzavJ3iZe3Qd8zZ9c3UIixxZvmE vinaypalvirk51@gmail.com


    -----END OPENSSH PRIVATE KEY-----
