apiVersion: v1
kind: Secret
metadata:
  name: my-private-ssh-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: my-repo-creds
  url: git@github.com:vinaypalvirk51/Caledon.git
  type: git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIjyjwiLzQupeLGnS1NzETgJ2Y+vhjVaGBaVMpu2aYWu vinaypalvirk51@gmail.com



    -----END OPENSSH PRIVATE KEY-----
